# Generated by Django 5.2.12 on 2026-03-24 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelo_alter_cor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(blank=True, default=0, max_length=4, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True)),
                ('acessorios', models.ManyToManyField(related_name='veiculos', to='core.acessorio')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.cor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.modelo')),
            ],
        ),
    ]
